# Generated by Django 3.2.24 on 2024-03-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypePorfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Type Porfolio')),
                ('description', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Type Porfolio',
                'verbose_name_plural': 'Types Porfolio',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Order number')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Portfolio')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('description', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Description')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
                ('main_image', models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/image', verbose_name='Main image')),
                ('type_porfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_porfolio_set', to='gallery.typeporfolio', verbose_name='Type porfolio')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/image')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.portfolio')),
            ],
        ),
    ]
