# Generated by Django 3.2.24 on 2024-03-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Fullname')),
                ('email', models.EmailField(blank=True, default='', max_length=50, null=True, verbose_name='E-mail')),
                ('type_client', models.CharField(default='', max_length=128, verbose_name='Client')),
                ('object', models.CharField(default='', max_length=128, verbose_name='Object')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'contact',
            },
        ),
    ]
