# Generated by Django 3.2.24 on 2024-05-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_type_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='E-mail'),
        ),
    ]
