# Generated by Django 3.2.24 on 2024-03-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Order number')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Function')),
                ('is_main_function', models.BooleanField(blank=True, verbose_name='Is main function')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
                ('comment', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Function',
                'verbose_name_plural': 'functions',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Order number')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Language name')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, unique=True, verbose_name='Fullname')),
                ('degree', models.CharField(max_length=255, verbose_name='Degree')),
                ('about_me', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='About me')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
                ('year_experience', models.CharField(max_length=255, verbose_name='Number of years experience')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('freelance', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=15)),
                ('main_picture', models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/picture', verbose_name='Picture')),
                ('function_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_set', to='portfolioapp.function', verbose_name='Function')),
                ('language_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_set', to='portfolioapp.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'owner',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Order number')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Reviewer')),
                ('profession', models.CharField(blank=True, max_length=255, verbose_name='Profession')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Company')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
                ('picture', models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/image', verbose_name='Picture')),
                ('message', models.CharField(blank=True, max_length=1024, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'review',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Order number')),
                ('skill_name', models.CharField(max_length=255, unique=True, verbose_name='Skill')),
                ('percent', models.CharField(blank=True, max_length=50, verbose_name='Percent')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Sociallink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
                ('icon_name', models.CharField(default='', max_length=128, verbose_name='Icon name (css)')),
                ('name', models.CharField(max_length=1024, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Social link',
                'verbose_name_plural': 'social links',
            },
        ),
        migrations.CreateModel(
            name='TypeQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Type Quality')),
                ('comment', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Type Quality',
                'verbose_name_plural': 'Types Quality',
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Order number')),
                ('quality_name', models.CharField(max_length=255, unique=True, verbose_name='Quality')),
                ('location', models.CharField(choices=[('Company', 'Company'), ('University', 'University')], default='Company', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Start date')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('description', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Description')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('social_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sociallink_owner_set', to='portfolioapp.sociallink', verbose_name='Social link')),
            ],
            options={
                'verbose_name': 'Quality',
                'verbose_name_plural': 'quality',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/picture')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.owner')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='social_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_link', to='portfolioapp.sociallink', verbose_name='Social link'),
        ),
    ]
