# Generated by Django 3.2.24 on 2024-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_auto_20240323_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='link',
            field=models.CharField(default='', max_length=1024, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Social'),
        ),
    ]
