# Generated by Django 3.2.24 on 2024-04-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_auto_20240413_0714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
