# Generated by Django 3.2.24 on 2024-04-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_delete_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Order number')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Language name')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.owner')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'languages',
            },
        ),
    ]
