# Generated by Django 3.2.24 on 2024-04-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='function_owner',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='is_main_function',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='social_link',
        ),
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.DeleteModel(
            name='Sociallink',
        ),
    ]
