# Generated by Django 3.2.24 on 2024-04-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_auto_20240413_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sociallink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Social')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
                ('icon_name', models.CharField(default='', max_length=128, verbose_name='Icon name (css)')),
                ('link', models.CharField(default='', max_length=1024, verbose_name='Link')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.owner')),
            ],
            options={
                'verbose_name': 'Social link',
                'verbose_name_plural': 'social links',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Order number')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Function')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
                ('comment', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Comment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.owner')),
            ],
            options={
                'verbose_name': 'Function',
                'verbose_name_plural': 'functions',
            },
        ),
    ]
