# Generated by Django 3.2.24 on 2024-04-13 08:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0009_alter_owner_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='about_me',
            field=tinymce.models.HTMLField(default='', verbose_name='About me'),
        ),
    ]
