# Generated by Django 3.2.24 on 2024-04-21 05:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0010_alter_owner_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='Description'),
        ),
    ]
