# Generated by Django 3.2.24 on 2024-04-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0011_alter_quality_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quality',
        ),
        migrations.DeleteModel(
            name='TypeQuality',
        ),
    ]
