# Generated by Django 3.2.24 on 2024-04-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0012_auto_20240421_0618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
