# Generated by Django 3.2.24 on 2024-04-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0013_delete_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='main_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/picture', verbose_name='Picture'),
        ),
    ]
