# Generated by Django 3.2.24 on 2024-05-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0014_alter_owner_main_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/image', verbose_name='Picture'),
        ),
    ]
