# Generated by Django 3.2.24 on 2024-03-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Order number')),
                ('service_name', models.CharField(max_length=255, unique=True, verbose_name='Service')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('description', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Description')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
                ('icon_name', models.CharField(default='', max_length=128, verbose_name='Icon name (css)')),
                ('image', models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/image', verbose_name='Image')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'services',
            },
        ),
    ]
