# Generated by Django 3.2.24 on 2024-04-21 06:18

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Type Quality')),
                ('comment', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Type Quality',
                'verbose_name_plural': 'Types Quality',
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Order number')),
                ('quality_name', models.CharField(max_length=255, unique=True, verbose_name='Quality')),
                ('location', models.CharField(choices=[('Company', 'Company'), ('University', 'University')], default='Company', max_length=100)),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('description', tinymce.models.HTMLField(default='', verbose_name='Description')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('type_quality', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='type_quality_owner_set', to='quality.typequality', verbose_name='Type Quality')),
            ],
            options={
                'verbose_name': 'Quality',
                'verbose_name_plural': 'quality',
            },
        ),
    ]
