# Generated by Django 3.2.24 on 2024-04-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='location',
            field=models.CharField(choices=[('Company', 'Company'), ('University', 'University')], default='', max_length=100),
        ),
    ]
