# Generated by Django 3.2.24 on 2024-04-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_alter_quality_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='location',
            field=models.CharField(choices=[('Company', 'Company'), ('University', 'University')], default=None, max_length=100),
        ),
    ]
