# Generated by Django 3.2.24 on 2024-04-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_alter_quality_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place'),
        ),
    ]
