# Generated by Django 3.2.24 on 2024-04-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Order number')),
                ('skill_name', models.CharField(max_length=255, unique=True, verbose_name='Skill')),
                ('percent', models.CharField(blank=True, max_length=50, verbose_name='Percent')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'skills',
            },
        ),
    ]
