# Generated by Django 3.2.24 on 2024-04-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='position',
            field=models.CharField(choices=[('Left', 'Align Left'), ('Rigth', 'Align Rigth')], default='Left', max_length=15),
        ),
    ]
