# Generated by Django 3.2.24 on 2024-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_remove_skill_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Color'),
        ),
    ]
